USE [master]
GO

/****** Object:  Database [BookmarksDB]    Script Date: 25-Jul-13 03:33:26 ******/
CREATE DATABASE [BookmarksDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookmarksDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BookmarksDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookmarksDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BookmarksDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BookmarksDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookmarksDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookmarksDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookmarksDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookmarksDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookmarksDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookmarksDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookmarksDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookmarksDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BookmarksDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookmarksDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookmarksDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookmarksDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookmarksDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookmarksDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookmarksDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookmarksDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookmarksDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookmarksDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookmarksDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookmarksDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookmarksDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookmarksDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookmarksDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookmarksDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookmarksDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BookmarksDB] SET  MULTI_USER 
GO

ALTER DATABASE [BookmarksDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookmarksDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookmarksDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookmarksDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BookmarksDB] SET  READ_WRITE 
GO

