USE [master]
GO

/****** Object:  Database [Bookstore]    Script Date: 25-Jul-13 18:06:55 ******/
CREATE DATABASE [Bookstore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bookstore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Bookstore.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Bookstore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Bookstore_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Bookstore] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bookstore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bookstore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bookstore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bookstore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bookstore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bookstore] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bookstore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bookstore] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Bookstore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bookstore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bookstore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bookstore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bookstore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bookstore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bookstore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bookstore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bookstore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bookstore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bookstore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bookstore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bookstore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bookstore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bookstore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bookstore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bookstore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Bookstore] SET  MULTI_USER 
GO

ALTER DATABASE [Bookstore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bookstore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bookstore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bookstore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Bookstore] SET  READ_WRITE 
GO

